# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-17 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_site', '0002_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='bollywood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameone', models.CharField(max_length=40, null=True, unique=True)),
                ('descriptionone', models.CharField(max_length=100, null=True)),
                ('dateone', models.DateField(blank=True, null=True)),
                ('durationone', models.DurationField(blank=True, null=True)),
                ('pictureone', models.ImageField(blank=True, null=True, upload_to='static')),
                ('Pathone', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
