# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-17 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_site', '0003_bollywood'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bollywood',
            new_name='bollywoodone',
        ),
    ]
