# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-17 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_site', '0004_auto_20190117_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='hollywoodthree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namethree', models.CharField(max_length=40, null=True, unique=True)),
                ('descriptionthree', models.CharField(max_length=100, null=True)),
                ('datethree', models.DateField(blank=True, null=True)),
                ('durationthree', models.DurationField(blank=True, null=True)),
                ('picturethree', models.ImageField(blank=True, null=True, upload_to='static')),
                ('Paththree', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tollywoodtwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nametwo', models.CharField(max_length=40, null=True, unique=True)),
                ('descriptiontwo', models.CharField(max_length=100, null=True)),
                ('datetwo', models.DateField(blank=True, null=True)),
                ('durationtwo', models.DurationField(blank=True, null=True)),
                ('picturetwo', models.ImageField(blank=True, null=True, upload_to='static')),
                ('Pathtwo', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
