# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-17 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_site', '0005_hollywoodthree_tollywoodtwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='upcomingone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namefour', models.CharField(max_length=40, null=True, unique=True)),
                ('picturefour', models.ImageField(blank=True, null=True, upload_to='static')),
            ],
        ),
        migrations.CreateModel(
            name='upcomingtwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namefive', models.CharField(max_length=40, null=True, unique=True)),
                ('descriptionfive', models.CharField(max_length=100, null=True)),
                ('datefive', models.DateField(blank=True, null=True)),
                ('picturefive', models.ImageField(blank=True, null=True, upload_to='static')),
            ],
        ),
    ]
