# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-18 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_site', '0006_upcomingone_upcomingtwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='toprating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namesix', models.CharField(max_length=40, null=True, unique=True)),
                ('descriptionsix', models.CharField(max_length=100, null=True)),
                ('datesix', models.DateField(blank=True, null=True)),
                ('durationsix', models.DurationField(blank=True, null=True)),
                ('picturesix', models.ImageField(blank=True, null=True, upload_to='mysite/movie_site/static/images')),
                ('Pathsix', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
