# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-26 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_site', '0008_auto_20190121_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Path',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
