# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-02 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_site', '0011_auto_20190128_0351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bollywoodone',
        ),
        migrations.DeleteModel(
            name='hollywoodthree',
        ),
        migrations.DeleteModel(
            name='tollywoodtwo',
        ),
        migrations.DeleteModel(
            name='upcomingone',
        ),
        migrations.DeleteModel(
            name='upcomingtwo',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Path',
        ),
        migrations.AddField(
            model_name='movie',
            name='catagory',
            field=models.IntegerField(blank=True, choices=[(1, 'Bollywood'), (2, 'Hollywood'), (3, 'Tollywood'), (4, 'UpcomingFirst'), (5, 'UpcomingTwo')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='path',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
